import express from 'express';
import cors from "cors";
import connectDB from "./db/connection.js";
import authRoutes from './routes/auth.js';
import categoryRoutes from './routes/Category.js';
import supplierRoutes from './routes/supplier.js';
import productRoutes from './routes/product.js';
import userRoutes from './routes/User.js';
import orderRoutes from './routes/order.js';
import dashboardRoutes from './routes/dashboard.js';
import dotenv from "dotenv";
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/auth', authRoutes);
app.use('/api/category', categoryRoutes );
app.use('/api/supplier', supplierRoutes );
app.use('/api/products', productRoutes );
app.use('/api/users', userRoutes );
app.use('/api/orders', orderRoutes );
app.use('/api/dashboard', dashboardRoutes );
app.listen(process.env.PORT, () => {
    connectDB();
console.log(`server is running on port http://localhost:${process.env.PORT}`);
});